CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327011256_InitialSchema') THEN
    CREATE TABLE areas (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(128) NOT NULL,
        "ContentHash" character varying(64) NOT NULL,
        "Neighbors" jsonb NOT NULL,
        CONSTRAINT "PK_areas" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327011256_InitialSchema') THEN
    CREATE TABLE game_versions (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Version" character varying(32) NOT NULL,
        "ExtractedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_game_versions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327011256_InitialSchema') THEN
    CREATE TABLE provinces (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "AreaId" integer NOT NULL,
        "Name" character varying(128) NOT NULL,
        "Paths" jsonb NOT NULL,
        CONSTRAINT "PK_provinces" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_provinces_areas_AreaId" FOREIGN KEY ("AreaId") REFERENCES areas ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327011256_InitialSchema') THEN
    CREATE TABLE game_version_areas (
        "GameVersionId" integer NOT NULL,
        "AreaId" integer NOT NULL,
        CONSTRAINT "PK_game_version_areas" PRIMARY KEY ("GameVersionId", "AreaId"),
        CONSTRAINT "FK_game_version_areas_areas_AreaId" FOREIGN KEY ("AreaId") REFERENCES areas ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_game_version_areas_game_versions_GameVersionId" FOREIGN KEY ("GameVersionId") REFERENCES game_versions ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327011256_InitialSchema') THEN
    CREATE TABLE locations (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ProvinceId" integer NOT NULL,
        "Name" character varying(128) NOT NULL,
        "Color" character varying(6) NOT NULL,
        "Topography" character varying(64) NOT NULL,
        "Climate" character varying(64) NOT NULL,
        "Vegetation" character varying(64),
        "RawMaterial" character varying(64),
        "Rank" character varying(32) NOT NULL,
        "CityX" double precision,
        "CityY" double precision,
        "Paths" jsonb NOT NULL,
        CONSTRAINT "PK_locations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_locations_provinces_ProvinceId" FOREIGN KEY ("ProvinceId") REFERENCES provinces ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327011256_InitialSchema') THEN
    CREATE UNIQUE INDEX "IX_areas_Name_ContentHash" ON areas ("Name", "ContentHash");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327011256_InitialSchema') THEN
    CREATE INDEX "IX_game_version_areas_AreaId" ON game_version_areas ("AreaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327011256_InitialSchema') THEN
    CREATE UNIQUE INDEX "IX_game_versions_Version" ON game_versions ("Version");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327011256_InitialSchema') THEN
    CREATE UNIQUE INDEX "IX_locations_ProvinceId_Name" ON locations ("ProvinceId", "Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327011256_InitialSchema') THEN
    CREATE UNIQUE INDEX "IX_provinces_AreaId_Name" ON provinces ("AreaId", "Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327011256_InitialSchema') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260327011256_InitialSchema', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260329174746_AddAreaHierarchy') THEN
    ALTER TABLE areas ADD "Continent" character varying(128);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260329174746_AddAreaHierarchy') THEN
    ALTER TABLE areas ADD "Region" character varying(128);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260329174746_AddAreaHierarchy') THEN
    ALTER TABLE areas ADD "SubContinent" character varying(128);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260329174746_AddAreaHierarchy') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260329174746_AddAreaHierarchy', '8.0.11');
    END IF;
END $EF$;
COMMIT;

